// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: transaction_id.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionIDService_GetNewTransactionID_FullMethodName = "/transaction.TransactionIDService/GetNewTransactionID"
)

// TransactionIDServiceClient is the client API for TransactionIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionIDServiceClient interface {
	GetNewTransactionID(ctx context.Context, in *TransactionIDRequest, opts ...grpc.CallOption) (*TransactionIDResponse, error)
}

type transactionIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionIDServiceClient(cc grpc.ClientConnInterface) TransactionIDServiceClient {
	return &transactionIDServiceClient{cc}
}

func (c *transactionIDServiceClient) GetNewTransactionID(ctx context.Context, in *TransactionIDRequest, opts ...grpc.CallOption) (*TransactionIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionIDResponse)
	err := c.cc.Invoke(ctx, TransactionIDService_GetNewTransactionID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionIDServiceServer is the server API for TransactionIDService service.
// All implementations must embed UnimplementedTransactionIDServiceServer
// for forward compatibility.
type TransactionIDServiceServer interface {
	GetNewTransactionID(context.Context, *TransactionIDRequest) (*TransactionIDResponse, error)
	mustEmbedUnimplementedTransactionIDServiceServer()
}

// UnimplementedTransactionIDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionIDServiceServer struct{}

func (UnimplementedTransactionIDServiceServer) GetNewTransactionID(context.Context, *TransactionIDRequest) (*TransactionIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewTransactionID not implemented")
}
func (UnimplementedTransactionIDServiceServer) mustEmbedUnimplementedTransactionIDServiceServer() {}
func (UnimplementedTransactionIDServiceServer) testEmbeddedByValue()                              {}

// UnsafeTransactionIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionIDServiceServer will
// result in compilation errors.
type UnsafeTransactionIDServiceServer interface {
	mustEmbedUnimplementedTransactionIDServiceServer()
}

func RegisterTransactionIDServiceServer(s grpc.ServiceRegistrar, srv TransactionIDServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionIDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionIDService_ServiceDesc, srv)
}

func _TransactionIDService_GetNewTransactionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionIDServiceServer).GetNewTransactionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionIDService_GetNewTransactionID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionIDServiceServer).GetNewTransactionID(ctx, req.(*TransactionIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionIDService_ServiceDesc is the grpc.ServiceDesc for TransactionIDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionIDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionIDService",
	HandlerType: (*TransactionIDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNewTransactionID",
			Handler:    _TransactionIDService_GetNewTransactionID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction_id.proto",
}
